### ISSUE TITLE
devel check encountered error

### ISSUE THREAD

**Issue by pjhalsli** [Almehdi/pachist#12]
when I update my system and it comes to pachist, this shows;
:: Searching AUR for updates...
:: Checking development packages...
 -> devel check for package failed: '/usr/bin/git ls-remote git://github.com/shellkr/pachist.git master' encountered an error
 
 Not sure if this is something serious but thought I should mention it.
 Still very grateful for this fantastic helpful script

**Comment by shellkr** [comment]
I think it is about the removal of support for 'git://' addresses... so I probably just have to change the PKGBUILD a bit. Will do that soonish and I am fairly confident it will work after that.. ;)
