### ISSUE TITLE
Add support for printing a specific range of lines

### ISSUE THREAD

**Issue by Almehdi** [Almehdi/pachist#6]
Now with the --quiet option it got me thinking. It would be nice to have ability to select a specific range of lines instead of the tail based we have now. The syntax should be kept as close as possible to the one already existing but smarter. 

ex..
    `pachist -q 3-5`
    `pachist -q {3,4,6}`

or something similar...

**Comment by silentboatman** [comment]
Yeah that would be interesting! 3-5 in your example, is that row 3 to 5 counting from the bottom?

Another thing I started to think about was if it would be useful to be able to filter from the command line. For instance, if you would like to filter out only recent installed packages, you could do something like:
```
pachist -q --filter install
```

**Comment by Almehdi** [comment]
Yes, exactly like that... I have been playing around a bit but not got anything working as i wanted yet. It has to be simple. I don't want to add too many lines if I don't need and I think this shouldn't need that.

Yes, that should be doable. A more elegant solution to the "filter" variables we have now should suffice.
