### ISSUE TITLE
search by date

### ISSUE THREAD

**Issue by Almehdi** [Almehdi/pachist#9]
Would be cool to be able to search by date.. you maybe want to go back to a date and see what you installed that day.

**Comment by silentboatman** [comment]
Yeah that would be great. And maybe not to much work if we use the same code we use when adding boot time :)  .

And by using `date` the user can format the date string in a lot of different ways. Like `pachist --date yesterday` and `pachist --date 2014-06-01` to just name a few.

**Comment by silentboatman** [comment]
This started me thinking. If we're going to add different features, we should split filter_and_format_output() into two function. To make it more readable (as we talked about before).

What do you think about this https://github.com/silentboatman/pachist/blob/split_awk/pachist

**Comment by Almehdi** [comment]
Yes, i support that notion... we might even have to split it even more depending. `Filter` are about parsing out the information we want from the log. `Format` are about making it look like we want. One idea would be to give every flag it's own function. I don't think that is needed just yet but such a scheme would make things much easier to read. We should also start commenting a bit better. ;)
